### ISSUE TITLE
[Suggestion] Some ideas

### ISSUE THREAD

**Issue by matcldr** [Arthed-Studios/SmartMoving#2]
API where you can modify values inside other plugins.
For example (maxjumps, minimumDistance...)
Ability  to modify value/player 

Function-wise, maybe "wall running or climbing" could be an excellent function to add.

**Comment by IPECTER** [comment]
I will add Event and API!

**Comment by IPECTER** [comment]
Use SmartMoving jar as Library
`SmartMovingManager.getInstance().getPlayer(org.bukkit.entity.Player)`
